name: Restore Database from Azure To PaaS

on:
  workflow_dispatch:
  schedule: # 03:00 UTC Mon-Fri
    - cron: '0 3 * * 1-5'

jobs:
  backup:
    name: Restore Database
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        environment: [qa, staging, production1, sandbox]
        include:
          - environment: production1
            NAME_SUFFIX: prod
    steps:
    - name: Restore Azure DB to PaaS ${{ matrix.environment }}
      run: echo $POSTGRES_SERVICE_INSTANCE
      env:
        POSTGRES_SERVICE_INSTANCE: apply-postgres-${{ matrix.NAME_SUFFIX || matrix.environment }}
